version: '3.9'
services:
  ggea_db:
    image: postgres:latest
    container_name: ggea_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - postgresql_ggea_db_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5433:5432

  ggea_db_editor:
    image: adminer
    container_name: ggea_db_editor
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 8080
    ports:
      - 8081:8080
    depends_on:
      - ggea_db

  ggea_backend:
    container_name: ggea_backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend/
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - BACKEND_SERVER_HOST=${BACKEND_SERVER_HOST}
      - BACKEND_SERVER_PORT=${BACKEND_SERVER_PORT}
      - BACKEND_SERVER_WORKERS=${BACKEND_SERVER_WORKERS}
      - STATIC_FILE_DIRECTORY=${STATIC_FILE_DIRECTORY}
      - DB_TIMEOUT=${DB_TIMEOUT}
      - DB_POOL_SIZE=${DB_POOL_SIZE}
      - DB_MAX_POOL_CON=${DB_MAX_POOL_CON}
      - DB_POOL_OVERFLOW=${DB_POOL_OVERFLOW}
      - IS_DB_ECHO_LOG=${IS_DB_ECHO_LOG}
      - IS_DB_EXPIRE_ON_COMMIT=${IS_DB_EXPIRE_ON_COMMIT}
      - IS_DB_FORCE_ROLLBACK=${IS_DB_FORCE_ROLLBACK}
      - IS_ALLOWED_CREDENTIALS=${IS_ALLOWED_CREDENTIALS}
      - API_TOKEN=${API_TOKEN}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_SUBJECT=${JWT_SUBJECT}
      - JWT_TOKEN_PREFIX=${JWT_TOKEN_PREFIX}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_MIN=${JWT_MIN}
      - JWT_HOUR=${JWT_HOUR}
      - JWT_DAY=${JWT_DAY}
      - HASHING_ALGORITHM_LAYER_1=${HASHING_ALGORITHM_LAYER_1}
      - HASHING_ALGORITHM_LAYER_2=${HASHING_ALGORITHM_LAYER_2}
      - HASHING_SALT=${HASHING_SALT}
      - ALLOWED_ORIGIN_1a=${ALLOWED_ORIGIN_1a}
      - ALLOWED_ORIGIN_1b=${ALLOWED_ORIGIN_1b}
      - ALLOWED_ORIGIN_1c=${ALLOWED_ORIGIN_1c}
      - ALLOWED_ORIGIN_1d=${ALLOWED_ORIGIN_1d}
      - ALLOWED_ORIGIN_2a=${ALLOWED_ORIGIN_2a}
      - ALLOWED_ORIGIN_2b=${ALLOWED_ORIGIN_2b}
      - ALLOWED_ORIGIN_2c=${ALLOWED_ORIGIN_2c}
      - ALLOWED_ORIGIN_2d=${ALLOWED_ORIGIN_2d}
      - ALLOWED_METHOD_1=${ALLOWED_METHOD_1}
      - ALLOWED_HEADER_1=${ALLOWED_HEADER_1}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_BUCKET_ARN=${AWS_S3_BUCKET_ARN}
      - AWS_S3_POKEMON_IMAGE_URI=${AWS_S3_POKEMON_IMAGE_URI}
      - AWS_S3_SKLEARN_MODEL_URI=${AWS_S3_SKLEARN_MODEL_URI}
      - AWS_S3_TF_MODEL_URI=${AWS_S3_TF_MODEL_URI}
      - AWS_S3_PT_MODEL_URI=${AWS_S3_PT_MODEL_URI}
      - AWS_IAM_USERNAME=${AWS_IAM_USERNAME}
      - AWS_IAM_ARN=${AWS_IAM_ARN}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SERVICE_NAME=${AWS_SERVICE_NAME}
      - AWS_SERVICE_REGION=${AWS_SERVICE_REGION}
      - TF_MODEL_FILE_EXTENSION=${TF_MODEL_FILE_EXTENSION}
      - SKLEARN_MODEL_FILE_EXTENSION=${SKLEARN_MODEL_FILE_EXTENSION}
      - PYTORCH_MODEL_FILE_EXTENSION=${PYTORCH_MODEL_FILE_EXTENSION}
      - AWS_S3_POKEMON_IMAGE_DIR=${AWS_S3_POKEMON_IMAGE_DIR}
      - AWS_S3_SKLEARN_MODEL_DIR=${AWS_S3_SKLEARN_MODEL_DIR}
      - AWS_S3_TF_MODEL_DIR=${AWS_S3_TF_MODEL_DIR}
      - AWS_S3_PT_MODEL_DIR=${AWS_S3_PT_MODEL_DIR}
    volumes:
      - ./backend/:/usr/backend/
    expose:
      - 8000
    ports:
      - 8001:8000
    depends_on:
      - ggea_db

volumes:
  postgresql_ggea_db_data:
