name: 'Backend: Continuous DeploymentðŸš€'
env:
  IMAGE: docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/backend

on:
  push:
    branches:
      - 'trunk'
jobs:
  deploy:
    name: 'Backend Deployment to Heroku ðŸ“¡'
    environment: heroku_production
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: 'ggea-web-api'
      HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to GitHub Packages
        run: echo ${TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          TOKEN: ${{ secrets.CICD_GITHUB_TOKEN }}
      - name: Pull the latest Docker image
        run: |
          docker pull ${{ env.IMAGE }}:latest || true
      - name: Build production image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }}:latest \
            --tag ${{ env.IMAGE }}:latest \
            --file ./backend/Dockerfile.production \
            "./backend"
      - name: Log in to the Heroku Container Registry
        run: docker login -u _ -p ${{ secrets.HEROKU_TOKEN }} registry.heroku.com
      - name: Tag the image
        run: docker tag ${{ env.IMAGE }}:latest ${{ env.HEROKU_REGISTRY_IMAGE }}
      - name: Push to the Heroku registry
        run: docker push ${{ env.HEROKU_REGISTRY_IMAGE }}
      - name: Set environment variables
        run: |
          echo "HEROKU_REGISTRY_IMAGE=${{ env.HEROKU_REGISTRY_IMAGE }}" >> $GITHUB_ENV
          echo "HEROKU_TOKEN=${{ secrets.HEROKU_TOKEN }}" >> $GITHUB_ENV
      - name: Release into production
        run: |
          chmod +x ./release.sh
          ./release.sh
